// <auto-generated />
namespace Tiqri.AMS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class referenceno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(referenceno));
        
        string IMigrationMetadata.Id
        {
            get { return "201710040511097_referenceno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
